SUBROUTINE BIO_READ_ALL(FN, M, N, YY, LDY, WW, LDW, JJ, INFO)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: FN
  INTEGER, INTENT(IN) :: M, N, LDY, LDW
  DOUBLE COMPLEX, INTENT(OUT) :: YY(LDY,N), WW(LDW,N)
  INTEGER, INTENT(OUT) :: JJ(M), INFO

  INTEGER :: U

  IF (LEN_TRIM(FN) .LE. 0) THEN
     INFO = -1
  ELSE IF (M .LT. 0) THEN
     INFO = -2
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE IF (N .GT. M) THEN
     INFO = -3
  ELSE IF (LDY .LT. M) THEN
     INFO = -5
  ELSE IF (LDW .LT. M) THEN
     INFO = -7
  ELSE
     INFO = 0
  END IF
  IF (INFO .NE. 0) RETURN

  U = -1

  CALL BIO_OPEN(U, TRIM(FN)//'.YY', 'RO', INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_READ_C2(U, M, N, YY, LDY, INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_CLOSE(U, INFO)
  IF (INFO .NE. 0) RETURN

  CALL BIO_OPEN(U, TRIM(FN)//'.WW', 'RO', INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_READ_C2(U, M, N, WW, LDW, INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_CLOSE(U, INFO)
  IF (INFO .NE. 0) RETURN

  CALL BIO_OPEN(U, TRIM(FN)//'.JJ', 'RO', INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_READ_I1(U, M, JJ, INFO)
  CALL BIO_CLOSE(U, INFO)
  IF (INFO .NE. 0) RETURN
END SUBROUTINE BIO_READ_ALL

SUBROUTINE BIO_WRITE_ALL(FN, N, Y, LDY, W, LDW, J, P, INFO)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: FN
  INTEGER, INTENT(IN) :: N, LDY, LDW, J(N), P(N)
  DOUBLE COMPLEX, INTENT(IN) :: Y(LDY,N), W(LDW,N)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: U

  IF (LEN_TRIM(FN) .LE. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -2
  ELSE IF (LDY .LT. N) THEN
     INFO = -4
  ELSE IF (LDW .LT. N) THEN
     INFO = -6
  ELSE
     INFO = 0
  END IF
  IF (INFO .NE. 0) RETURN

  U = -1

  CALL BIO_OPEN(U, TRIM(FN)//'.Y', 'WO', INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_WRITE_C2(U, N, N, Y, LDY, INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_CLOSE(U, INFO)
  IF (INFO .NE. 0) RETURN

  CALL BIO_OPEN(U, TRIM(FN)//'.W', 'WO', INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_WRITE_C2(U, N, N, W, LDW, INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_CLOSE(U, INFO)
  IF (INFO .NE. 0) RETURN

  CALL BIO_OPEN(U, TRIM(FN)//'.J', 'WO', INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_WRITE_I1(U, N, J, INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_CLOSE(U, INFO)
  IF (INFO .NE. 0) RETURN

  CALL BIO_OPEN(U, TRIM(FN)//'.P', 'WO', INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_WRITE_I1(U, N, P, INFO)
  IF (INFO .NE. 0) RETURN
  CALL BIO_CLOSE(U, INFO)
  IF (INFO .NE. 0) RETURN
END SUBROUTINE BIO_WRITE_ALL
