MODULE DTYPES
  USE PARAMS
  IMPLICIT NONE

  TYPE ZSHENT
     COMPLEX(KIND=DWP), POINTER, CONTIGUOUS :: Y(:,:) => NULL()
     COMPLEX(KIND=DWP), POINTER, CONTIGUOUS :: W(:,:) => NULL()
     COMPLEX(KIND=DWP), POINTER, CONTIGUOUS :: Z(:,:) => NULL()
  END TYPE ZSHENT

  TYPE Z1MEM
     COMPLEX(KIND=DWP), POINTER, CONTIGUOUS :: X(:,:) => NULL()
     COMPLEX(KIND=DWP), POINTER, CONTIGUOUS :: T(:,:) => NULL()
     COMPLEX(KIND=DWP), POINTER, CONTIGUOUS :: Y(:,:) => NULL()
     REAL(KIND=DWP), POINTER, CONTIGUOUS :: U(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: IPIV(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: JVEC(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: IPL(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: INVP(:) => NULL()
  END TYPE Z1MEM

CONTAINS
END MODULE DTYPES
