MODULE DTYPES
  USE PARAMS
  IMPLICIT NONE

  TYPE CSHENT
     COMPLEX, POINTER, CONTIGUOUS :: Y(:,:) => NULL()
     COMPLEX, POINTER, CONTIGUOUS :: W(:,:) => NULL()
     COMPLEX, POINTER, CONTIGUOUS :: Z(:,:) => NULL()
  END TYPE CSHENT
  TYPE ZSHENT
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: Y(:,:) => NULL()
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: W(:,:) => NULL()
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: Z(:,:) => NULL()
  END TYPE ZSHENT

CONTAINS
END MODULE DTYPES
