MODULE DTYPES
  USE PARAMS
  IMPLICIT NONE

  TYPE CSHENT
     COMPLEX, POINTER, CONTIGUOUS :: Y(:,:) => NULL()
     COMPLEX, POINTER, CONTIGUOUS :: W(:,:) => NULL()
     COMPLEX, POINTER, CONTIGUOUS :: Z(:,:) => NULL()
  END TYPE CSHENT
  TYPE ZSHENT
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: Y(:,:) => NULL()
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: W(:,:) => NULL()
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: Z(:,:) => NULL()
  END TYPE ZSHENT

  TYPE Z1MEM
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: X(:,:) => NULL()
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: T(:,:) => NULL()
     DOUBLE COMPLEX, POINTER, CONTIGUOUS :: Y(:,:) => NULL()
     DOUBLE PRECISION, POINTER, CONTIGUOUS :: U(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: IPIV(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: JVEC(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: IPL(:) => NULL()
     INTEGER, POINTER, CONTIGUOUS :: INVP(:) => NULL()
  END TYPE Z1MEM

CONTAINS
END MODULE DTYPES
