MODULE PARAMS
  USE, INTRINSIC :: ISO_C_BINDING
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INPUT_UNIT, OUTPUT_UNIT, ERROR_UNIT
  IMPLICIT NONE

  INTEGER, PARAMETER :: UINP = INPUT_UNIT
  INTEGER, PARAMETER :: UOUT = OUTPUT_UNIT
  INTEGER, PARAMETER :: ULOG = ERROR_UNIT

  INTEGER, PARAMETER :: LWP = KIND(.FALSE.)
  INTEGER, PARAMETER :: IWP = KIND(0)
  INTEGER, PARAMETER :: SWP = KIND(0.0E0)
  INTEGER, PARAMETER :: DWP = KIND(0.0D0)

  ! Cache line size in bytes.
  ! Valid for Intel CPUs, needs changing for e.g. POWER (128 B).
  INTEGER, PARAMETER :: CLSIZB = 64
  ! Max SIMD vector length in bytes.
  ! Valid for Intel AVX-512, otherwise smaller (but >= 16 B).
  INTEGER, PARAMETER :: SIMDLB = 64
  ! Alignment in bytes = max(cache line size, vector length)
  INTEGER, PARAMETER :: ALIGNB = MAX(CLSIZB, SIMDLB)

  INTEGER, PARAMETER :: LSIMDL = SIMDLB / SIZEOF(.FALSE.)
  INTEGER, PARAMETER :: ISIMDL = SIMDLB / SIZEOF(0)
  INTEGER, PARAMETER :: SSIMDL = SIMDLB / SIZEOF(0.0E0)
  INTEGER, PARAMETER :: DSIMDL = SIMDLB / SIZEOF(0.0D0)
  INTEGER, PARAMETER :: CSIMDL = SSIMDL / 2
  INTEGER, PARAMETER :: ZSIMDL = DSIMDL / 2

  INTEGER, PARAMETER :: LALIGN = ALIGNB / SIZEOF(.FALSE.)
  INTEGER, PARAMETER :: IALIGN = ALIGNB / SIZEOF(0)
  INTEGER, PARAMETER :: SALIGN = ALIGNB / SIZEOF(0.0E0)
  INTEGER, PARAMETER :: DALIGN = ALIGNB / SIZEOF(0.0D0)
  INTEGER, PARAMETER :: CALIGN = SALIGN / 2
  INTEGER, PARAMETER :: ZALIGN = DALIGN / 2

  INTEGER, PARAMETER :: MAXCPR = 96 ! max. number of 2nd-level threads
  INTEGER, PARAMETER :: MAXTPC = 64 ! max. number of 1st-level threads

  REAL, PARAMETER :: S_ZERO  =  0.0E0
  REAL, PARAMETER :: S_ONE   =  1.0E0
  REAL, PARAMETER :: S_MONE  = -1.0E0

  COMPLEX, PARAMETER :: C_ZERO  = (S_ZERO, S_ZERO)
  COMPLEX, PARAMETER :: C_ONE   = (S_ONE , S_ZERO)
  COMPLEX, PARAMETER :: C_MONE  = (S_MONE, S_ZERO)
  COMPLEX, PARAMETER :: C_IONE  = (S_ZERO, S_ONE )
  COMPLEX, PARAMETER :: C_MIONE = (S_ZERO, S_MONE)

  DOUBLE PRECISION, PARAMETER :: D_ZERO =  0.0D0
  DOUBLE PRECISION, PARAMETER :: D_ONE  =  1.0D0
  DOUBLE PRECISION, PARAMETER :: D_MONE = -1.0D0
  DOUBLE PRECISION, PARAMETER :: D_TWO  =  2.0D0
  DOUBLE PRECISION, PARAMETER :: D_MTWO = -2.0D0

  DOUBLE PRECISION, PARAMETER :: D_PI   = 3.1415926535897932384626433832795D0
  DOUBLE PRECISION, PARAMETER :: D_PI_2 = 1.5707963267948966192313216916398D0
  DOUBLE PRECISION, PARAMETER :: D_PI_4 = 7.8539816339744830961566084581988D-1

  DOUBLE COMPLEX, PARAMETER :: Z_ZERO  = (D_ZERO, D_ZERO)
  DOUBLE COMPLEX, PARAMETER :: Z_ONE   = (D_ONE , D_ZERO)
  DOUBLE COMPLEX, PARAMETER :: Z_MONE  = (D_MONE, D_ZERO)
  DOUBLE COMPLEX, PARAMETER :: Z_IONE  = (D_ZERO, D_ONE )
  DOUBLE COMPLEX, PARAMETER :: Z_MIONE = (D_ZERO, D_MONE)

CONTAINS

  PURE INTEGER FUNCTION LDALIGN(M, TALIGN)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: M, TALIGN

    INTEGER :: R

    IF (M .LE. TALIGN) THEN
       LDALIGN = TALIGN
    ELSE
       R = MOD(M, TALIGN)
       IF (R .EQ. 0) THEN
          LDALIGN = M
       ELSE
          LDALIGN = M + (TALIGN - R)
       END IF
    END IF
  END FUNCTION LDALIGN
END MODULE PARAMS
