! B = A^H (for a square A)
#ifndef MKL_NEST_SEQ
SUBROUTINE ZCOPYH(N, A,LDA, B,LDB, TPC)
#else
SUBROUTINE ZCOPYH(N, A,LDA, B,LDB)
#endif
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: N, LDA,LDB
#ifndef MKL_NEST_SEQ
  INTEGER, INTENT(IN) :: TPC
#endif
  DOUBLE COMPLEX, INTENT(IN) :: A(LDA,N)
  DOUBLE COMPLEX, INTENT(OUT) :: B(LDB,N)

  INTEGER :: I, J

#ifndef MKL_NEST_SEQ
  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(I,J) SHARED(A,B,N) NUM_THREADS(TPC) PROC_BIND(CLOSE)
#endif
  DO J = 1, N
     DO I = 1, N
        B(I,J) = DCONJG(A(J,I))
     END DO
  END DO
#ifndef MKL_NEST_SEQ
  !$OMP END PARALLEL DO
#endif
END SUBROUTINE ZCOPYH
