! B = A^H (for a square A)
SUBROUTINE ZCOPYH(N, A,LDA, B,LDB)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: N, LDA,LDB
  COMPLEX(KIND=DWP), INTENT(IN) :: A(LDA,N)
  COMPLEX(KIND=DWP), INTENT(OUT) :: B(LDB,N)

  INTEGER :: I, J

  DO J = 1, N
     DO I = 1, N
        B(I,J) = CONJG(A(J,I))
     END DO
  END DO
END SUBROUTINE ZCOPYH
