  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  HZ = 0
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  DHZ = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  RE_S_PP = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  RE_S_QQ = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  RE_S_PQ = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED  
  IM_S_PQ = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  AV_S_PQ = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  CA_S_PQ = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  SA_S_PQ = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  RE_H_PP = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  RE_H_QQ = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  RE_H_PQ = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  IM_H_PQ = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  AV_H_PQ = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  CA_H_PQ = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  SA_H_PQ = D_ONE
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  TG = D_ZERO
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  SG = D_ONE
