  ! S

  RE_S_PP(PIX) = D_ZERO
  RE_S_QQ(PIX) = D_ZERO
  RE_S_PQ(PIX) = D_ZERO
  IM_S_PQ(PIX) = D_ZERO

  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  DTMP1 = D_ZERO ! RE_S_PP
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  DTMP2 = D_ZERO ! RE_S_QQ
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  DTMP3 = D_ZERO ! RE_S_PQ
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  DTMP4 = D_ZERO ! IM_S_PQ
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  ZTMP1 = Z_ZERO ! ZP
  !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
  ZTMP2 = Z_ZERO ! ZQ

  DO I = 1, K, DSIMDL
     L = MIN(DSIMDL, K-(I-1))
     !DIR$ VECTOR ALWAYS ASSERT,ALIGNED
     DO J = 1, L
        ZTMP1(J) = BS(I+(J-1),P)
        ZTMP2(J) = BS(I+(J-1),Q)
        DTMP1(J) = DTMP1(J) + (DBLE(ZTMP1(J))*DBLE(ZTMP1(J)) + AIMAG(ZTMP1(J))*AIMAG(ZTMP1(J))) !DBLE(DCONJG(ZTMP1(J))*ZTMP1(J))
        DTMP2(J) = DTMP2(J) + (DBLE(ZTMP2(J))*DBLE(ZTMP2(J)) + AIMAG(ZTMP2(J))*AIMAG(ZTMP2(J))) !DBLE(DCONJG(ZTMP2(J))*ZTMP2(J))
        ! += DCONJG(ZTMP1(J)) * ZTMP2(J)
        DTMP3(J) = DTMP3(J) + (DBLE(ZTMP1(J))*DBLE(ZTMP2(J)) + AIMAG(ZTMP1(J))*AIMAG(ZTMP2(J)))
        DTMP4(J) = DTMP4(J) + (DBLE(ZTMP1(J))*AIMAG(ZTMP2(J))- AIMAG(ZTMP1(J))*DBLE(ZTMP2(J)))
     END DO
  END DO

  RE_S_PP(PIX) = SUM(DTMP1)
  RE_S_QQ(PIX) = SUM(DTMP2)
  RE_S_PQ(PIX) = SUM(DTMP3)
  IM_S_PQ(PIX) = SUM(DTMP4)

  IF (RE_S_PP(PIX) .NE. RE_S_PP(PIX)) THEN
     ! NaN
     STOP 'ZHZL1: NaN(S_pp)'
  ELSE IF (RE_S_PP(PIX) .LE. D_ZERO) THEN
     ! should never happen
     STOP 'ZHZL1: S_pp .LE. 0'
  ELSE IF (RE_S_PP(PIX) .GT. HUGE(D_ZERO)) THEN
     ! overflow
     ! A joint prescaling of BH and BS needed...
     STOP 'ZHZL1: Infinity(S_pp)'
  ELSE IF (RE_S_PP(PIX) .NE. D_ONE) THEN
     RE_S_PP(PIX) = D_ONE / SQRT(RE_S_PP(PIX))
  END IF

  IF (RE_S_QQ(PIX) .NE. RE_S_QQ(PIX)) THEN
     ! NaN
     STOP 'ZHZL1: NaN(S_qq)'
  ELSE IF (RE_S_QQ(PIX) .LE. D_ZERO) THEN
     ! should never happen
     STOP 'ZHZL1: S_qq .LE. 0'
  ELSE IF (RE_S_QQ(PIX) .GT. HUGE(D_ZERO)) THEN
     ! overflow
     ! A joint prescaling of BH and BS needed...
     STOP 'ZHZL1: Infinity(S_qq)'
  ELSE IF (RE_S_QQ(PIX) .NE. D_ONE) THEN
     RE_S_QQ(PIX) = D_ONE / SQRT(RE_S_QQ(PIX))
  END IF
