! B = G^H G (J = I)
SUBROUTINE ZIMUL(M,N, G,LDG, B,LDB)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: M,N, LDG,LDB
  COMPLEX(KIND=DWP), INTENT(IN) :: G(LDG,N)
  COMPLEX(KIND=DWP), INTENT(OUT) :: B(LDB,N)

  EXTERNAL :: ZHERK

  CALL ZHERK('L','C', N,M, D_ONE, G,LDG, D_ZERO, B,LDB)
END SUBROUTINE ZIMUL
