! B = F^H J F (J =/= I)
SUBROUTINE ZJMUL(M,N, F,JF, LDF, JNSTIX,JNLENS,JNBLKS, B, LDB)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: M,N, LDF,LDB
  INTEGER, INTENT(IN) :: JNBLKS,JNSTIX(JNBLKS),JNLENS(JNBLKS)
  DOUBLE COMPLEX, INTENT(IN) :: F(LDF,N)
  DOUBLE COMPLEX, INTENT(OUT) :: JF(LDF,N), B(LDB,N)

  EXTERNAL :: ZLACPY, ZGEMM

  CALL ZLACPY('A', M,N, F,LDF, JF,LDF)
  CALL ZJSCL(N, JF,LDF, JNSTIX,JNLENS,JNBLKS)
  CALL ZGEMM('C','N', N,N,M, Z_ONE, F,LDF, JF,LDF, Z_ZERO, B,LDB)
END SUBROUTINE ZJMUL
