! B = F^H J F (J =/= I)
#ifndef MKL_NEST_SEQ
SUBROUTINE ZJMUL(M,N, F,JF, LDF, J,JNSTIX,JNLENS,JNBLKS, B, LDB, TPC)
#else
SUBROUTINE ZJMUL(M,N, F,JF, LDF, J,JNSTIX,JNLENS,JNBLKS, B, LDB)
#endif
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: M,N, LDF,LDB, J(M),JNBLKS,JNSTIX(JNBLKS),JNLENS(JNBLKS)
#ifndef MKL_NEST_SEQ
  INTEGER, INTENT(IN) :: TPC
#endif
  DOUBLE COMPLEX, INTENT(IN) :: F(LDF,N)
  DOUBLE COMPLEX, INTENT(OUT) :: JF(LDF,N), B(LDB,N)

  EXTERNAL :: ZLACPY, ZGEMM

  CALL ZLACPY('A', M,N, F,LDF, JF,LDF)
#ifndef MKL_NEST_SEQ
  CALL ZJSCL(M,N, JF,LDF, J,JNSTIX,JNLENS,JNBLKS, TPC)
#else
  CALL ZJSCL(M,N, JF,LDF, J,JNSTIX,JNLENS,JNBLKS)
#endif
  CALL ZGEMM('C','N', N,N,M, Z_ONE, F,LDF, JF,LDF, Z_ZERO, B,LDB)
END SUBROUTINE ZJMUL
