! B = F^H J F (J =/= I)
#ifdef HAVE_J_SCALE
#ifndef MKL_NEST_SEQ
SUBROUTINE ZJMUL(M,N, F,JF, LDF, J,JNSTIX,JNLENS,JNBLKS, B, LDB, TPC)
#else
SUBROUTINE ZJMUL(M,N, F,JF, LDF, J,JNSTIX,JNLENS,JNBLKS, B, LDB)
#endif
#else
#ifndef MKL_NEST_SEQ
SUBROUTINE ZJMUL(M,N, F,JF, LDF, JNSTIX,JNLENS,JNBLKS, B, LDB, TPC)
#else
SUBROUTINE ZJMUL(M,N, F,JF, LDF, JNSTIX,JNLENS,JNBLKS, B, LDB)
#endif
#endif
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: M,N, LDF,LDB
#ifdef HAVE_J_SCALE
  INTEGER, INTENT(IN) :: J(M)
#endif
  INTEGER, INTENT(IN) :: JNBLKS,JNSTIX(JNBLKS),JNLENS(JNBLKS)
#ifndef MKL_NEST_SEQ
  INTEGER, INTENT(IN) :: TPC
#endif
  DOUBLE COMPLEX, INTENT(IN) :: F(LDF,N)
  DOUBLE COMPLEX, INTENT(OUT) :: JF(LDF,N), B(LDB,N)

  EXTERNAL :: ZLACPY, ZGEMM

  CALL ZLACPY('A', M,N, F,LDF, JF,LDF)
#ifdef HAVE_J_SCALE
#ifndef MKL_NEST_SEQ
  CALL ZJSCL(M,N, JF,LDF, J,JNSTIX,JNLENS,JNBLKS, TPC)
#else
  CALL ZJSCL(M,N, JF,LDF, J,JNSTIX,JNLENS,JNBLKS)
#endif
#else
#ifndef MKL_NEST_SEQ
  CALL ZJSCL(N, JF,LDF, JNSTIX,JNLENS,JNBLKS, TPC)
#else
  CALL ZJSCL(N, JF,LDF, JNSTIX,JNLENS,JNBLKS)
#endif
#endif
  CALL ZGEMM('C','N', N,N,M, Z_ONE, F,LDF, JF,LDF, Z_ZERO, B,LDB)
END SUBROUTINE ZJMUL
