! TGT_F = J SRC_F
SUBROUTINE ZJSCL(N, JF,LDF, JNSTIX,JNLENS,JNBLKS)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: N, LDF
  INTEGER, INTENT(IN) :: JNBLKS,JNSTIX(JNBLKS),JNLENS(JNBLKS)
  DOUBLE COMPLEX, INTENT(INOUT) :: JF(LDF,N)

  INTEGER :: I,I1,I2, K

  DO K = 1, N
     DO I1 = 1, JNBLKS
        I2 = JNSTIX(I1) + JNLENS(I1) - 1
        DO I = JNSTIX(I1), I2
           JF(I,K) = -JF(I,K)
        END DO
     END DO
  END DO
END SUBROUTINE ZJSCL
