! Z = partOf(I)
SUBROUTINE ZSETZI(M,N1,N2, Z1,Z2,LDZ, IFC1,IFC2)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: M,N1,N2, LDZ, IFC1,IFC2
  COMPLEX(KIND=DWP), INTENT(OUT) :: Z1(LDZ,N1),Z2(LDZ,N2)

  EXTERNAL :: ZLASET

#ifdef NDEBUG
  !DIR$ ASSUME (M .GE. 0)
  !DIR$ ASSUME (N1 .GE. 0)
  !DIR$ ASSUME (N2 .GE. 0)
  !DIR$ ASSUME (LDZ .GE. M)
  !DIR$ ASSUME (IFC1 .GE. 1)
  !DIR$ ASSUME (IFC1 .LE. M)
  !DIR$ ASSUME (IFC2 .GE. 1)
  !DIR$ ASSUME (IFC2 .LE. M)
#else
  IF (M .LT. 0) STOP 'ZSETZI: M .LT. 0'
  IF (N1 .LT. 0) STOP 'ZSETZI: N1 .LT. 0'
  IF (N2 .LT. 0) STOP 'ZSETZI: N2 .LT. 0'
  IF (LDZ .LT. M) STOP 'ZSETZI: LDZ .LT. M'
  IF (IFC1 .LT. 1) STOP 'ZETZI: IFC1 .LT. 1'
  IF (IFC1 .GT. M) STOP 'ZETZI: IFC1 .GT. M'
  IF (IFC2 .LT. 1) STOP 'ZETZI: IFC2 .LT. 1'
  IF (IFC2 .GT. M) STOP 'ZETZI: IFC2 .GT. M'
#endif

  CALL ZLASET('A', IFC1-1,    N1, Z_ZERO, Z_ZERO, Z1,LDZ)
  CALL ZLASET('A', (M-IFC1)+1,N1, Z_ZERO, Z_ONE,  Z1(IFC1,1),LDZ)
  CALL ZLASET('A', IFC2-1,    N2, Z_ZERO, Z_ZERO, Z2,LDZ)
  CALL ZLASET('A', (M-IFC2)+1,N2, Z_ZERO, Z_ONE,  Z2(IFC2,1),LDZ)
END SUBROUTINE ZSETZI
