SUBROUTINE ZUPDATE(M,N, A1,A2,LDA, BZ,LDB, LNOROT)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: M,N, LDA, LDB
  LOGICAL, INTENT(IN) :: LNOROT
  COMPLEX(KIND=DWP), INTENT(IN) :: A1(LDA,N), BZ(LDB,N)
  COMPLEX(KIND=DWP), INTENT(OUT) :: A2(LDA,N)

  EXTERNAL :: ZGEMM, ZLACPY

  IF (LNOROT) THEN
     CALL ZLACPY('A', M,N, A1,LDA, A2,LDA)
  ELSE ! BZ =/= I
     CALL ZGEMM('N','N', M,N,N, Z_ONE, A1,LDA, BZ,LDB, Z_ZERO, A2,LDA)
  END IF
END SUBROUTINE ZUPDATE
