SUBROUTINE ZXFER2(M,N1,N2, A1,A2, LDA, B1,B2, LDB)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M,N1,N2, LDA,LDB
  COMPLEX(KIND=DWP), INTENT(IN) :: A1(LDA,N1),A2(LDA,N2)
  COMPLEX(KIND=DWP), INTENT(OUT) :: B1(LDB,N1),B2(LDB,N2)

  EXTERNAL :: ZLACPY

#ifdef NDEBUG
  !DIR$ ASSUME (M .GE. 0)
  !DIR$ ASSUME (N1 .GE. 0)
  !DIR$ ASSUME (N2 .GE. 0)
  !DIR$ ASSUME (LDA .GE. M)
  !DIR$ ASSUME (LDB .GE. M)
#else
  IF (M .LT. 0) STOP 'ZXFER2: M .LT. 0'
  IF (N1 .LT. 0) STOP 'ZXFER2: N1 .LT. 0'
  IF (N2 .LT. 0) STOP 'ZXFER2: N2 .LT. 0'
  IF (LDA .LT. M) STOP 'ZXFER2: LDA .LT. M'
  IF (LDB .LT. M) STOP 'ZXFER2: LDB .LT. M'
#endif

  CALL ZLACPY('A', M,N1, A1,LDA, B1,LDB)
  CALL ZLACPY('A', M,N2, A2,LDA, B2,LDB)
END SUBROUTINE ZXFER2
