SUBROUTINE READCL(FN, M, N, CPR, TPC, JSTRAT, NSWP, INFO)
  IMPLICIT NONE
  CHARACTER(LEN=*,KIND=c_char), INTENT(OUT) :: FN
  INTEGER, INTENT(OUT) :: M, N, CPR, TPC, JSTRAT(2), NSWP(2), INFO

  CHARACTER(LEN=FNL) :: ARG
  INTEGER :: TMP

  INFO = 0
  IF (COMMAND_ARGUMENT_COUNT() .NE. 9) STOP 'phase3.exe FN M N CPR TPC JSTRAT1 NSWP1 JSTRAT2 NSWP2'

  CALL GET_COMMAND_ARGUMENT(1, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -1
     RETURN
  END IF
  FN = TRIM(ARG)
  IF (LEN_TRIM(FN) .LE. 0) THEN
     INFO = 1
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(2, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -2
     RETURN
  END IF
  READ (ARG,*) M
  IF (M .LE. 0) THEN
     INFO = 2
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(3, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -3
     RETURN
  END IF
  READ (ARG,*) N
  IF (N .LE. 0) THEN
     INFO = 3
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(4, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -4
     RETURN
  END IF
  READ (ARG,*) CPR
  IF ((CPR .LE. 0) .OR. (CPR .GT. MAXCPR)) THEN
     INFO = 4
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(5, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -5
     RETURN
  END IF
  READ (ARG,*) TPC
  IF ((TPC .LT. 0) .OR. (TPC .GT. MAXTPC)) THEN
     INFO = 5
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(6, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -6
     RETURN
  END IF
  READ (ARG,*) JSTRAT(1)
  IF ((JSTRAT(1) .LT. 0) .OR. (JSTRAT(1) .GT. JSMMWC)) THEN
     INFO = 6
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(7, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -7
     RETURN
  END IF
  READ (ARG,*) NSWP(1)
  IF (NSWP(1) .LT. 0) THEN
     INFO = 7
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(8, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -8
     RETURN
  END IF
  READ (ARG,*) JSTRAT(2)
  IF ((JSTRAT(2) .LT. 0) .OR. (JSTRAT(2) .GT. JSMMWC)) THEN
     INFO = 8
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(9, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -9
     RETURN
  END IF
  READ (ARG,*) NSWP(2)
  IF (NSWP(2) .LT. 0) THEN
     INFO = 9
     RETURN
  END IF
END SUBROUTINE READCL
