SUBROUTINE READCL(FN, L, a, G, TPC, INFO)
  IMPLICIT NONE
  CHARACTER(LEN=*,KIND=c_char), INTENT(OUT) :: FN
  INTEGER, INTENT(OUT) :: L, a, G, TPC, INFO

  CHARACTER(LEN=FNL) :: ARG
  INTEGER :: TMP

  IF (COMMAND_ARGUMENT_COUNT() .NE. 5) STOP 'phase1.exe FN L a G TPC'

  CALL GET_COMMAND_ARGUMENT(1, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -1
     RETURN
  END IF
  FN = TRIM(ARG)
  IF (LEN_TRIM(FN) .LE. 0) THEN
     INFO = 1
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(2, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -2
     RETURN
  END IF
  READ (ARG,*) L
  IF (L .LE. 0) THEN
     INFO = 2
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(3, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -3
     RETURN
  END IF
  READ (ARG,*) a
  IF (a .LE. 0) THEN
     INFO = 3
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(4, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -4
     RETURN
  END IF
  READ (ARG,*) G
  IF (G .LE. 0) THEN
     INFO = 4
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(5, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -5
     RETURN
  END IF
  READ (ARG,*) TPC
  IF ((TPC .LE. 0) .OR. (TPC .GT. MAXTPC)) THEN
     INFO = 5
     RETURN
  END IF
END SUBROUTINE READCL
