  SUBROUTINE BREAD_Z(FD, Z, N, SZ, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FD, N
    DOUBLE COMPLEX, INTENT(OUT), TARGET :: Z(N,N)
    INTEGER, INTENT(OUT) :: SZ, INFO

    INFO = 0

    SZ = BREAD(FD, C_LOC(Z), C_SIZEOF(Z), 0)
    IF (SZ .NE. C_SIZEOF(Z)) INFO = 1
  END SUBROUTINE BREAD_Z

  SUBROUTINE BWRITE_ZZ(FD, ZZ, N, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FD, N
    DOUBLE COMPLEX, INTENT(IN), TARGET :: ZZ(N,N)
    INTEGER, INTENT(OUT) :: INFO

    INFO = BWRITE(FD, C_LOC(ZZ), C_SIZEOF(ZZ), 0)
  END SUBROUTINE BWRITE_ZZ
