  SUBROUTINE BREAD_Z(FD, Z, N, SZ, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FD, N
    REAL(KIND=DWP), INTENT(OUT), TARGET :: Z(N,N)
    INTEGER, INTENT(OUT) :: SZ, INFO

    INTEGER :: I, J

    SZ = N * C_SIZEOF(D_ZERO)
    INFO = 0

    !$OMP PARALLEL DEFAULT(NONE) PRIVATE(I,J) SHARED(Z,N,FD,SZ) REDUCTION(MAX:INFO)
    INFO = 0
    !$OMP DO
    DO J = 1, N
       I = BREAD(FD, C_LOC(Z(1,J)), SZ, (J-1) * SZ)
       IF (I .NE. SZ) INFO = MAX(INFO,J)
    END DO
    !$OMP END DO
    !$OMP END PARALLEL

    SZ = SZ * N
  END SUBROUTINE BREAD_Z

  SUBROUTINE BWRITE_ZZ(FD, ZZ, N, SZ, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: FD, N
    REAL(KIND=DWP), INTENT(IN), TARGET :: ZZ(N,N)
    INTEGER, INTENT(OUT) :: SZ, INFO

    INTEGER :: I, J

    SZ = N * C_SIZEOF(D_ZERO)
    INFO = 0

    !$OMP PARALLEL DEFAULT(NONE) PRIVATE(I,J) SHARED(ZZ,N,FD,SZ) REDUCTION(MAX:INFO)
    INFO = 0
    !$OMP DO
    DO J = 1, N
       I = BWRITE(FD, C_LOC(ZZ(1,J)), SZ, (J-1) * SZ)
       IF (I .NE. SZ) INFO = MAX(INFO,J)
    END DO
    !$OMP END DO
    !$OMP END PARALLEL

    SZ = SZ * N
  END SUBROUTINE BWRITE_ZZ
