SUBROUTINE READCL(FN, N, INFO)
  IMPLICIT NONE
  CHARACTER(LEN=*,KIND=c_char), INTENT(OUT) :: FN
  INTEGER, INTENT(OUT) :: N, INFO

  CHARACTER(LEN=FNL) :: ARG
  INTEGER :: TMP

  INFO = 0
  IF (COMMAND_ARGUMENT_COUNT() .NE. 2) STOP 'phase4.exe FN N'

  CALL GET_COMMAND_ARGUMENT(1, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -1
     RETURN
  END IF
  FN = TRIM(ARG)
  IF (LEN_TRIM(FN) .LE. 0) THEN
     INFO = 1
     RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(2, ARG, TMP, INFO)
  IF (INFO .NE. 0) THEN
     INFO = -2
     RETURN
  END IF
  READ (ARG,*) N
  IF (N .LE. 0) THEN
     INFO = 2
     RETURN
  END IF
END SUBROUTINE READCL
